### PR TITLE
Add support for changing VendorID / ProductID

### PR DESCRIPTION
**Pull request by spuder**
## Problem

The PID/VID of the usb devices appears as ExpressIf

Screenshot 2024-03-22 at 10 01 49 PM

Plugging in the device on OSX prompts the user to identify the keyboard type
keyboard type

## Solution

Adds build parameters that allow the user to overwrite the VendorID/ProductID and Product Description. 

```bash
    -D USB_VID=0x05ac
    -D USB_PID=0x0267
    -D USB_MANUFACTURER='"Apple Inc."'
```
Screenshot 2024-03-22 at 9 34 48 PM

### CODE REVIEW

**Comment by wasdwasd0105** [comment]
Let me have some tests!

**Comment by spuder** [comment]
I can add tests. 

It appears there aren't any tests yet. [Which framework do you prefer?](https://docs.platformio.org/en/stable/advanced/unit-testing/index.html) 

- Doctest
- GoogleTest
- Unity
- Custom

**Comment by wasdwasd0105** [comment]
I just test if the code can run on my devices. It looks good. I have one question, how can I rename Espressif ESP32-S2-Kaluga-1 Kit?

**Comment by spuder** [comment]
> I just test if the code can run on my devices. It looks good. I have one question, how can I rename Espressif ESP32-S2-Kaluga-1 Kit?

Where are you seeing `Espressif ESP32-S2-Kaluga-1 Kit` ? 

The USB_MANUFACTURER flag should rename the device in the OS. Maybe I'm misunderstanding where you are seeing Expressif still shown. 

```
    -D USB_VID=0x05ac
    -D USB_PID=0x0267
    -D USB_MANUFACTURER='"Apple Inc."'
```

**Comment by wasdwasd0105** [comment]
Screenshot 2024-05-08 at 1 58 59 PM

**Comment by wasdwasd0105** [comment]
Yes! It looks good!

**Pull request merged**
